name: syringe
description: Syringe is a dependency injection (DI) library for Dart applications.
version: 0.9.8-pre
repository: https://github.com/karbunkul/dart_syringe

topics:
  - di
  - dependency

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
